spring:
  profiles:
    default: common

  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile:

#logging:
#  level:
#    root: INFO
#    org.springframework.boot.autoconfigure: DEBUG
