spring:
  application:
    name: POC R2DBC (MongoDB)
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: orders
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
