spring:
  application:
    name: POC R2DBC (Mongo)
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/orders
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  data:
    mongodb:
      host: localhost
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/orders
      port: 27017
      database: orders
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB}
  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
